<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<Version>3.0.0</Version>
		<UserSecretsId>ca07f3be-343d-4cb5-8a4d-8cd5574d739b</UserSecretsId>
		<TableStorageSerializerContext>PulseGuard.Models.PulseSerializerContext</TableStorageSerializerContext>
		<EnableLoggingGenerator>true</EnableLoggingGenerator>
		<NoWarn>$(NoWarn);IDE0051</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" />
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Azure.Monitor.Query.Logs" />
		<PackageReference Include="Azure.ResourceManager.AppService" />
		<PackageReference Include="Azure.Storage.Blobs" />
		<PackageReference Include="Azure.Storage.Queues" />
		<PackageReference Include="FastExpressionCompiler" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="OpenTelemetry.Api" />
		<PackageReference Include="Polly" />
		<PackageReference Include="protobuf-net" />
		<PackageReference Include="protobuf-net.BuildTools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Yarp.ReverseProxy" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Formatting.Compact" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="SecureWebhooks.SystemTextJson" />
		<PackageReference Include="Sqids" />
		<PackageReference Include="TableStorage" />
		<PackageReference Include="TableStorage.Blobs" />
		<PackageReference Include="TableStorage.Blobs.RuntimeCompilations" />
		<PackageReference Include="TableStorage.Core" />
		<PackageReference Include="TableStorage.Fluent" />
		<PackageReference Include="TableStorage.Fluent.RuntimeCompilations" />
		<PackageReference Include="TableStorage.RuntimeCompilations" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PulseGuard.Views.V3\PulseGuard.Views.V3.esproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\PulseGuard.Storage.Abstractions\PulseGuard.Storage.Abstractions.csproj" />
		<ProjectReference Include="..\PulseGuard.Storage.Azure\PulseGuard.Storage.Azure.csproj" />
		<ProjectReference Include="..\PulseGuard.Storage.Postgres\PulseGuard.Storage.Postgres.csproj" />
	</ItemGroup>

	<Target Name="TruncateSourceRevisionId" BeforeTargets="AddSourceRevisionToInformationalVersion" Condition="'$(SourceRevisionId)' != '' and $(SourceRevisionId.Length) &gt; 7">
		<PropertyGroup>
			<SourceRevisionId>$(SourceRevisionId.Substring(0, 7))</SourceRevisionId>
		</PropertyGroup>
	</Target>

</Project>
